### ISSUE TITLE
Webpack & Babel

### ISSUE THREAD

**Issue by chasm** [jurca/indexed-db.es6#15]
Is there an easy way to use this with Webpack and Babel? I'm already building a React.js site in ES6, but I don't transpile the node modules. Looking at this, it looks like I'd have to do that to indexed-db.es6. I could load it and traceur I guess and run it at runtime, but that slows load times and means I'm using both Babel and Traceur.

Do you have a recommendation? I'd love to use this.

**Comment by jurca** [comment]
I don't have much experience with Webpack, but you should be able to use Babel.
Just transpile the files in the `es6`/ directory using Babel and use the output, it should work just fine.

Sorry for the longer time to reply, I wasn't watching this project for some reason.

Let me know if you run into any issues.

**Comment by askmatey** [comment]
See jurca/indexed-db.es6#16

**Comment by jurca** [comment]
I think this issue is resolved, then :)
