### ISSUE TITLE
Best method to filter by boolean value

### ISSUE THREAD

**Issue by 84564221** [jurca/indexed-db.es6#17]
I am looking for a simple method, to filter records by an `boolean` value. According to the documentation, the `filter` value can be either

``` txt
?(undefined|number|string|Date|Array|IDBKeyRange|Object<string, (number|string|Date|Array|IDBKeyRange)>|function(*, (number|string|Date|Array)): boolean)=} filter
```

See https://github.com/jurca/indexed-db.es6/blob/master/es6/object-store/query-engine.js

Example usage:

``` js

// The filter
const bestFriendFilter = {
  buddy: true
}

// The query
database.getObjectStore('batmans_friends')
               .query(bestFriendFilter, null)
               .then((records) => {
  // Expected result
  console.log(records); // [{id: 2, name: "Robin", driverLicense: false, buddy: true}]
});
```

``` sh
DataError: Data provided to an operation does not meet requirements.
```

However, the above example does not work, but I was able to run the filter by using a `function` like this:

``` js
function(record) {
  return record.buddy === true;
}
```

@jurca What is the recommended way, to run query filters?

**Comment by jurca** [comment]
Hello,

you filter object does not match the `Object<string, (number|string|Date|Array|IDBKeyRange)>` type. The problem with using `boolean`s in filter is that `boolean` is not a valid IndexedDB key type - this is a limitation imposed by the IndexedDB itself.

There are multiple ways to work around this limitation:

1) store the boolean flag as a number, a `1` for `true` and `0` for `false`
2) use a filter function, for example: `record => record.buddy`

The first one should have a better performance (if you create an index on the `buddy` field), the latter lets you to keep your boolean values.

I hope this helps :).

**Comment by askmatey** [comment]
Thanks mate
